const users = [
  {
    firstName: 'Joe',
    lastName: 'Bloggs',
    userName: 'joe-bloggs',
    value: 'joe-bloggs',
    label: 'Joe Bloggs',
  },
  {
    firstName: 'Jane',
    lastName: 'Madows',
    userName: 'jane-madows',
    value: 'jane-madows',
    label: 'Jane Madows',
  },
  {
    firstName: 'Mark',
    lastName: 'Redfern',
    userName: 'mark-redfern',
    value: 'mark-redfern',
    label: 'Mark Redfern',
  },
  {
    firstName: 'Tony',
    lastName: 'Hitchman',
    userName: 'tony-hitchman',
    value: 'tony-hitchman',
    label: 'Tony Hitchman',
  },
  {
    firstName: 'Chris',
    lastName: 'Duckett',
    userName: 'chris-duckett',
    value: 'chris-duckett',
    label: 'Chris Duckett',
  },
  {
    firstName: 'James',
    lastName: 'Evans',
    userName: 'james-evans',
    value: 'james-evans',
    label: 'James Evans',
  },
  {
    firstName: 'Liam',
    lastName: 'Roberts',
    userName: 'liam-roberts',
    value: 'liam-roberts',
    label: 'Liam Roberts',
  },
  {
    firstName: 'Scott',
    lastName: 'Dainton',
    userName: 'scott-dainton',
    value: 'scott-dainton',
    label: 'Scott Dainton',
  },
];

const buildings = [
  {
    plan: 'PS724931',
    address: '100-106 High Street, North Sydney, 2060, NSW',
    value: 'PS724931',
    label: '100-106 High Street, North Sydney, 2060, NSW - #PS724931',
  },
  {
    plan: 'PS724932',
    address: '85 William Street, Darlinghurst, 2010, NSW',
    value: 'PS724932',
    label: '85 William Street, Darlinghurst, 2010, NSW - #PS724932',
  },
];

const lots = [
  { label: '2154', value: '2154' },
  { label: '2155', value: '2155' },
  { label: '2156', value: '2156' },
  { label: '2157', value: '2157' },
  { label: '2158', value: '2158' },
  { label: '2159', value: '2159' },
  { label: '2160', value: '2160' },
  { label: '2161', value: '2161' },
  { label: '2162', value: '2162' },
  { label: '2163', value: '2163' },
  { label: '2164', value: '2164' },
  { label: '2165', value: '2165' },
];

const categories = [
  { label: 'Minutes', value: 'minutes' },
  { label: 'Lease', value: 'lease' },
  { label: 'Financials', value: 'financials' },
  { label: 'Invoices', value: 'invoices' },
  { label: 'Misc', value: 'misc' },
];

module.exports = {
  buildings,
  lots,
  categories,
  users,
  filesArr: [
    {
      filetype: 'doc',
      name: 'Lease Agreement',
      category: 'Lease',
      size: 1400,
      uploaded: 1568815200,
      opened: false,
      action: false,
      id: 1,
    },
    {
      filetype: 'xls',
      name: 'March - June 2019 Spending',
      category: 'Financials',
      size: 120000,
      uploaded: 1568815200,
      opened: false,
      action: false,
      id: 2,
    },
    {
      filetype: 'pdf',
      name: 'Floor Plan',
      category: 'Misc',
      size: 15000,
      uploaded: 1568815200,
      opened: false,
      action: false,
      id: 3,
    },
    {
      filetype: 'pdf',
      name: 'Landscaping Invoice',
      category: 'Invoices',
      size: 7600,
      uploaded: 1568815200,
      opened: false,
      action: false,
      id: 4,
    },
    {
      filetype: 'doc',
      name: 'Another Word Document',
      category: 'Misc',
      size: 10000,
      uploaded: 1568815200,
      opened: false,
      action: true,
      id: 5,
    },
    {
      filetype: 'doc',
      name: 'Locksmith Invoice',
      category: 'Invoices',
      size: 1500,
      uploaded: 1568815200,
      opened: false,
      action: false,
      id: 6,
    },
    {
      filetype: 'xls',
      name: 'Prices',
      category: 'Misc',
      size: 10000,
      uploaded: 1568815200,
      opened: false,
      action: true,
      id: 7,
    },
    {
      filetype: 'pdf',
      name: '01_project_description',
      category: 'Misc',
      size: 1700,
      uploaded: 1568815200,
      opened: false,
      action: false,
      id: 8,
    },
    {
      filetype: 'jpg',
      name: 'Landscaping Invoice',
      category: 'invoices',
      size: 1900,
      uploaded: 1569075200,
      opened: false,
      action: false,
      id: 9,
    },
    {
      filetype: 'mov',
      name: 'Previous Building Works',
      category: 'Misc',
      size: 1900,
      uploaded: 1569175200,
      opened: false,
      action: false,
      id: 10,
    },
    {
      filetype: 'pdf',
      name: 'Contract',
      category: 'Lease',
      size: 1900,
      uploaded: 1569275200,
      opened: false,
      action: false,
      id: 11,
    },
    {
      filetype: 'csv',
      name: 'Spending',
      category: 'Financials',
      size: 1900,
      uploaded: 1569375200,
      opened: false,
      action: true,
      id: 12,
    },
    {
      filetype: 'png',
      name: 'Finished Painting',
      category: 'Misc',
      size: 1900,
      uploaded: 1569475200,
      opened: false,
      action: true,
      id: 13,
    },
    {
      filetype: 'csv',
      name: 'Current Owners 01/03/2019',
      category: 'Misc',
      size: 1900,
      uploaded: 1569575200,
      opened: false,
      action: true,
      id: 14,
    },
    {
      filetype: 'pdf',
      name: 'Insurance Details',
      category: 'Misc',
      size: 1900,
      uploaded: 1569675200,
      opened: false,
      action: false,
      id: 15,
    },
    {
      filetype: 'pdf',
      name: 'Capital Works Fund',
      category: 'Financials',
      size: 1900,
      uploaded: 1569775200,
      opened: false,
      action: false,
      id: 16,
    },
    {
      filetype: 'jpeg',
      name: 'Broken Locks',
      category: 'Misc',
      size: 1900,
      uploaded: 1569875200,
      opened: false,
      action: false,
      id: 17,
    },
    {
      filetype: 'pdf',
      name: 'Plumbing Invoice',
      category: 'Invoices',
      size: 1900,
      uploaded: 1569975200,
      opened: false,
      action: true,
      id: 18,
    },
    {
      filetype: 'xls',
      name: 'Meeting Minutes Sep/19',
      category: 'Misc',
      size: 1900,
      uploaded: 1570075200,
      opened: false,
      action: false,
      id: 19,
    },
    {
      filetype: 'xls',
      name: 'Building Report',
      category: 'Misc',
      size: 1900,
      uploaded: 1570175200,
      opened: false,
      action: false,
      id: 20,
    },
    {
      filetype: 'doc',
      name: 'Lease Agreement',
      category: 'Lease',
      size: 1400,
      uploaded: 1568815200,
      opened: false,
      action: false,
      id: 21,
    },
    {
      filetype: 'xls',
      name: 'March - June 2019 Spending',
      category: 'Financials',
      size: 120000,
      uploaded: 1568815200,
      opened: false,
      action: false,
      id: 22,
    },
    {
      filetype: 'pdf',
      name: 'Floor Plan',
      category: 'Misc',
      size: 15000,
      uploaded: 1568815200,
      opened: false,
      action: false,
      id: 23,
    },
    {
      filetype: 'pdf',
      name: 'Landscaping Invoice',
      category: 'Invoices',
      size: 7600,
      uploaded: 1568815200,
      opened: false,
      action: false,
      id: 24,
    },
    {
      filetype: 'doc',
      name: 'Another Word Document',
      category: 'Misc',
      size: 10000,
      uploaded: 1568815200,
      opened: false,
      action: false,
      id: 25,
    },
    {
      filetype: 'doc',
      name: 'Locksmith Invoice',
      category: 'Invoices',
      size: 1500,
      uploaded: 1568815200,
      opened: false,
      action: false,
      id: 26,
    },
    {
      filetype: 'xls',
      name: 'Prices',
      category: 'Misc',
      size: 10000,
      uploaded: 1568815200,
      opened: false,
      action: true,
      id: 27,
    },
    {
      filetype: 'pdf',
      name: '01_project_description',
      category: 'Misc',
      size: 1700,
      uploaded: 1568815200,
      opened: false,
      action: false,
      id: 28,
    },
    {
      filetype: 'jpg',
      name: 'Landscaping Invoice',
      category: 'invoices',
      size: 1900,
      uploaded: 1569075200,
      opened: false,
      action: false,
      id: 29,
    },
    {
      filetype: 'mov',
      name: 'Previous Building Works',
      category: 'Misc',
      size: 1900,
      uploaded: 1569175200,
      opened: false,
      action: false,
      id: 30,
    },
    {
      filetype: 'pdf',
      name: 'Contract',
      category: 'Lease',
      size: 1900,
      uploaded: 1569275200,
      opened: false,
      action: false,
      id: 31,
    },
    {
      filetype: 'csv',
      name: 'Spending',
      category: 'Financials',
      size: 1900,
      uploaded: 1569375200,
      opened: false,
      action: false,
      id: 32,
    },
    {
      filetype: 'png',
      name: 'Finished Painting',
      category: 'Misc',
      size: 1900,
      uploaded: 1569475200,
      opened: false,
      action: true,
      id: 33,
    },
    {
      filetype: 'csv',
      name: 'Current Owners 01/03/2019',
      category: 'Misc',
      size: 1900,
      uploaded: 1569575200,
      opened: false,
      action: false,
      id: 34,
    },
    {
      filetype: 'pdf',
      name: 'Insurance Details',
      category: 'Misc',
      size: 1900,
      uploaded: 1569675200,
      opened: false,
      action: false,
      id: 35,
    },
    {
      filetype: 'pdf',
      name: 'Capital Works Fund',
      category: 'Financials',
      size: 1900,
      uploaded: 1569775200,
      opened: false,
      action: false,
      id: 36,
    },
    {
      filetype: 'jpeg',
      name: 'Broken Locks',
      category: 'Misc',
      size: 1900,
      uploaded: 1569875200,
      opened: false,
      action: false,
      id: 37,
    },
    {
      filetype: 'pdf',
      name: 'Plumbing Invoice',
      category: 'Invoices',
      size: 1900,
      uploaded: 1569975200,
      opened: false,
      action: false,
      id: 38,
    },
    {
      filetype: 'xls',
      name: 'Meeting Minutes Sep/19',
      category: 'Misc',
      size: 1900,
      uploaded: 1570075200,
      opened: false,
      action: false,
      id: 39,
    },
    {
      filetype: 'xls',
      name: 'Building Report',
      category: 'Misc',
      size: 1900,
      uploaded: 1570175200,
      opened: false,
      action: false,
      id: 40,
    },
    {
      filetype: 'doc',
      name: 'Lease Agreement',
      category: 'Lease',
      size: 1400,
      uploaded: 1568815200,
      opened: false,
      action: false,
      id: 41,
    },
    {
      filetype: 'xls',
      name: 'March - June 2019 Spending',
      category: 'Financials',
      size: 120000,
      uploaded: 1568815200,
      opened: false,
      action: false,
      id: 42,
    },
    {
      filetype: 'pdf',
      name: 'Floor Plan',
      category: 'Misc',
      size: 15000,
      uploaded: 1568815200,
      opened: false,
      action: false,
      id: 43,
    },
    {
      filetype: 'pdf',
      name: 'Landscaping Invoice',
      category: 'Invoices',
      size: 7600,
      uploaded: 1568815200,
      opened: false,
      action: false,
      id: 44,
    },
    {
      filetype: 'doc',
      name: 'Another Word Document',
      category: 'Misc',
      size: 10000,
      uploaded: 1568815200,
      opened: false,
      action: false,
      id: 45,
    },
    {
      filetype: 'doc',
      name: 'Locksmith Invoice',
      category: 'Invoices',
      size: 1500,
      uploaded: 1568815200,
      opened: false,
      action: false,
      id: 46,
    },
    {
      filetype: 'xls',
      name: 'Prices',
      category: 'Misc',
      size: 10000,
      uploaded: 1568815200,
      opened: false,
      action: false,
      id: 47,
    },
    {
      filetype: 'pdf',
      name: '01_project_description',
      category: 'Misc',
      size: 1700,
      uploaded: 1568815200,
      opened: false,
      action: false,
      id: 48,
    },
    {
      filetype: 'jpg',
      name: 'Landscaping Invoice',
      category: 'invoices',
      size: 1900,
      uploaded: 1569075200,
      opened: false,
      action: false,
      id: 49,
    },
    {
      filetype: 'mov',
      name: 'Previous Building Works',
      category: 'Misc',
      size: 1900,
      uploaded: 1569175200,
      opened: false,
      action: false,
      id: 50,
    },
    {
      filetype: 'pdf',
      name: 'Contract',
      category: 'Lease',
      size: 1900,
      uploaded: 1569275200,
      opened: false,
      action: false,
      id: 51,
    },
    {
      filetype: 'csv',
      name: 'Spending',
      category: 'Financials',
      size: 1900,
      uploaded: 1569375200,
      opened: false,
      action: true,
      id: 52,
    },
    {
      filetype: 'png',
      name: 'Finished Painting',
      category: 'Misc',
      size: 1900,
      uploaded: 1569475200,
      opened: false,
      action: false,
      id: 53,
    },
    {
      filetype: 'csv',
      name: 'Current Owners 01/03/2019',
      category: 'Misc',
      size: 1900,
      uploaded: 1569575200,
      opened: false,
      action: true,
      id: 54,
    },
    {
      filetype: 'pdf',
      name: 'Insurance Details',
      category: 'Misc',
      size: 1900,
      uploaded: 1569675200,
      opened: false,
      action: false,
      id: 55,
    },
    {
      filetype: 'pdf',
      name: 'Capital Works Fund',
      category: 'Financials',
      size: 1900,
      uploaded: 1569775200,
      opened: false,
      action: false,
      id: 56,
    },
    {
      filetype: 'jpeg',
      name: 'Broken Locks',
      category: 'Misc',
      size: 1900,
      uploaded: 1569875200,
      opened: false,
      action: false,
      id: 57,
    },
    {
      filetype: 'pdf',
      name: 'Plumbing Invoice',
      category: 'Invoices',
      size: 1900,
      uploaded: 1569975200,
      opened: false,
      action: false,
      id: 58,
    },
    {
      filetype: 'xls',
      name: 'Meeting Minutes Sep/19',
      category: 'Misc',
      size: 1900,
      uploaded: 1570075200,
      opened: false,
      action: false,
      id: 59,
    },
    {
      filetype: 'xls',
      name: 'Building Report',
      category: 'Misc',
      size: 1900,
      uploaded: 1570175200,
      opened: false,
      action: false,
      id: 60,
    },
  ],
  messageContent: [
    {
      user: users[0],
      message: 'Nunc consectetur finibus ante auctor pretium. Ut id tortor luctus, ultricies magna et, lacinia dui.',
      time: 1570635314,
      type: 'text',
    },
    {
      user: users[1],
      message: 'https://cdn.website.thryv.com/30df59d568e8470fa0db9a7f84282493/dms3rep/multi/1533053-cracked-window.jpg',
      time: 1570638914,
      type: 'image',
    },
    {
      user: users[0],
      message: 'Vivamus fermentum tellus eget nisi pharetra, nec varius ante pellentesque. Quisque convallis elit elit. Nulla.',
      time: 1570639514,
      type: 'text',
    },
    {
      user: users[2],
      message: 'Morbi tempus vulputate ipsum at facilisis. Nullam egestas ligula nec purus vehicula rutrum. Lorem ipsum.',
      time: 1570643414,
      type: 'text',
    },
    {
      user: users[2],
      message: 'Morbi tempus vulputate ipsum at facilisis. Nullam egestas ligula nec purus vehicula rutrum. Lorem ipsum.',
      time: 1570643418,
      type: 'text',
    },
    {
      user: users[0],
      message: 'Morbi tempus vulputate ipsum at facilisis. Nullam egestas ligula nec purus vehicula rutrum. Lorem ipsum.',
      time: 1570643534,
      type: 'text',
    },
    {
      user: users[2],
      message: 'Praesent aliquet neque tortor, dignissim tincidunt turpis fermentum vel. Vivamus metus ex, dictum quis mollis.',
      time: 1570644014,
      type: 'text',
    },
    {
      user: users[1],
      message: 'Vivamus fermentum tellus eget nisi pharetra, nec varius ante pellentesque. Quisque convallis elit elit. Nulla.',
      time: 1570644314,
      type: 'text',
    },
    {
      user: users[3],
      message: 'Nunc consectetur finibus ante auctor pretium. Ut id tortor luctus, ultricies magna et, lacinia dui.',
      time: 1570644374,
      type: 'text',
    },
  ],
};
